### ISSUE TITLE
allPlayers does not work

### ISSUE THREAD

**Issue by xXSchrandXx** [robinp7720/Blue-Stats-Minecraft#100]
Hi,
ibims mal wieder, ich hab Bluestats mal geupdated, und jetzt funktioniert die allPlayers Seite nicht mehr.
Seite, in die Bluestats eingebunden ist: https://www.gamestrike.de/index.php/CustomPage/?id=9
Seite, ohne Einbindung: https://www.gamestrike.de/stats/?page=allPlayers
Ich benutze nur lolmewnstats und die allPlayers.html vom standart Theme.

Mit freundlichen Gruß
xXSchrandXx

**Comment by robinp7720** [comment]
ajax Url ist nicht auf https eingestellt.

**Comment by xXSchrandXx** [comment]
ist jetzt Https, doch es funktioniert immer noch nicht.
Muss ich Rechte des Ordners speziell eingestellt haben?

**Comment by xXSchrandXx** [comment]
Und die Optionen vom allPlayers Modul stehen nicht im Unterpunkt "Modules" sondern bei "Plugins".
(Ich weiß nicht ob das so muss oder nicht, aber ich denke es sollte eigendlich zu "Modules"
