### ISSUE TITLE
Error trying to load home page

### ISSUE THREAD

**Issue by Hellcode48** [robinp7720/Blue-Stats-Minecraft#101]
Warning: mysqli::__construct(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/stats/classes/plugin/plugin.php on line 75
Base plugin does not exist:
Please install this plugin or change the base plugin
Notice: Trying to get property of non-object in /var/www/stats/modules/playerCount.php on line 3

Fatal error: Uncaught Error: Call to a member function count() on null in /var/www/stats/modules/playerCount.php:3 Stack trace: #0 /var/www/stats/classes/module.class.php(36): include() #1 /var/www/stats/classes/view.class.php(96): module->render() #2 /var/www/stats/classes/view.class.php(110): view->render('page') #3 /var/www/stats/classes/bluestats.class.php(75): view->render() #4 /var/www/stats/index.php(87): BlueStats->loadPage() #5 {main} thrown in /var/www/stats/modules/playerCount.php on line 3

**Comment by robinp7720** [comment]
The error shows that your BlueStats install cannot connect to the mysql server. Either you have not completed the installation or you have configured it with wrong credentials.

**Comment by Hellcode48** [comment]
its weird because the credentials is correct, is this config correct? 

{"mysql":{"username":"REDACTED","password":"REDACTED","dbname":"bluestats","host":"localhost"}}

**Comment by robinp7720** [comment]
Yes. That seams to look correct. Have you checked the credentials for the other mysql settings aswell. The error indicates that you have enabled a plugin during install but have not entered the mysql details to connect to the database

**Comment by Hellcode48** [comment]
I did, I have Statz, bluestats and query enabled, all settings correct

**Comment by Hellcode48** [comment]
And I just redid the config and install setup, and now it just shows: 


Warning: mysqli::__construct(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/stats/classes/plugin/plugin.php on line 75
Base plugin does not exist:
Please install this plugin or change the base plugin

**Comment by robinp7720** [comment]
The error still states that the mysql credentials are wrong for a BlueStats plugin. Please check and correct all the details in advanced admin panel of bluestats.
