### ISSUE TITLE
Base plugin not found

### ISSUE THREAD

**Issue by Ji-Rath** [robinp7720/Blue-Stats-Minecraft#102]
After installing bluestats onto my website, I get an error when I try to go to the home page of bluestats.

"Base plugin does not exist: 
Please install this plugin or change the base plugin"

However, I cannot seem to find where I can download the base plugin. Any help would be appreciated.

**Comment by robinp7720** [comment]
During install, you haven't enabled any plugin. You need to enable the plugins which you wish to use during installation. Simply re-install BlueStats and check the boxes for which plugins to enable.

**Comment by lukeeexd** [comment]
I'm still getting this error, doing fixinstall opens a blank page
