### ISSUE TITLE
General Help with Format

### ISSUE THREAD

**Issue by MCTyler** [robinp7720/Blue-Stats-Minecraft#104]
Hi, Sorry, but I didn't like the Monstrosity big heads so I shrunk them a bit but I can't find where to shrink the box now to fit the heads. Could you please point me to that section of the code.
![screenshot from 2018-02-22 19-02-17](https://user-images.githubusercontent.com/6390898/36572803-507118d0-1803-11e8-9d04-7b484e20bf86.png)

**Comment by MCTyler** [comment]
Also, I'm testing this on my Home Computer using Apache and Ubuntu and when I click on Player it says **http://mylocalip/player/uuid** not found. Any suggestions about what I did wrong here? I have query enabled in Server Properties and on the Web Suite, also of note, I'm using a Spigot 1.12.2 server.

**Comment by MCTyler** [comment]
Figured out the second part Enabled a2enmod rewrite and edited apache2.conf as follows....
<Directory /var/www/>
        Options Indexes FollowSymLinks
        **AllowOverride All**
        Require all granted
</Directory>

**Comment by robinp7720** [comment]
Column width is defined by bootstrap through the column width classes.
A column looks like this:
```html
<div class="col-md-3 col-sm-4 col-xs-6">
   <div class="panel panel-default">
      <img src="https://minotar.net/helm/spaceparticles/300.png" alt="" style="width:100%;">
      <div class="panel-body">
         <h3 style="margin-top:0;padding:0;">
            <a href="https://stats.mysunland.org/player/407329ad-83f5-4741-ab47-9179f26c1727/">spaceparticles</a>
         </h3>
         <h6 style="margin-top:0;padding:0;" class="text-muted">Teleported 2194 times</h6>
      </div>
   </div>
</div>
```

To change the width of this, simply change the ```col-md-3 col-sm-4 col-xs-6```. col-md controls the size on desktop sm on smaller displays and xs on phones. Total units is 12. ```col-md-3``` is 25% width. ```col-md-6``` is 50% width.

If you want to make it smaller on desktops, you could use ```col-md-2``` or ```col-md-1```.

This would be in the file ```/modules/topPlayers.php```
