### ISSUE TITLE
MySQLnd?

### ISSUE THREAD

**Issue by bayshiro** [robinp7720/Blue-Stats-Minecraft#14]
"Please install mysqlnd! 
Terminating for security reasons"

What should I do to fix this?

I understand the module has to be installed, and my web server is running on CentOS 6.5, but I just don't know how to do it...
Your instructions only include the Debian method, and the package name isn't the same for CentOS.

**Comment by robinp7720** [comment]
http://stackoverflow.com/questions/13159518/how-to-enable-mysqlnd-for-php

**Comment by bayshiro** [comment]
"yum install php-mysqlnd is only available on CentALT and maybe remi repos. Webtatic also has some good php repos as well. It is NOT on the default ones (I was using CentOS)."

None of the solutions on that page work for me.

**Comment by robinp7720** [comment]
As far as I know centALT doesnt exist anymore. yum is the package manager centos uses. Remember to uninstall the mysql extension first

**Comment by robinp7720** [comment]
Are you using a php mysql stack such as xampp or are you using a lamp setup?

**Comment by bayshiro** [comment]
I'm actually using the stack that comes with VestaCP (web control panel)
Attempting to "yum install php-mysqlnd" just results in "no package found"

**Comment by robinp7720** [comment]
Your on your own, I have never used centOS. If you use a paid linux host, they might use their own repo so use the default centOS one.

**Comment by roastnewt** [comment]
"yum install php-mysqlnd is only available on CentALT and maybe **remi repos**"

Have you tried:

```
yum --enablerepo=remi,remi-test remove php-mysql
yum --enablerepo=remi,remi-test install php-mysqlnd
```
