### ISSUE TITLE
Many a errors after installation

### ISSUE THREAD

**Issue by minegame30** [robinp7720/Blue-Stats-Minecraft#17]
Hello!
I downloaded the source code from here yesterday for BlueStats 3. I uploaded it to my webserver, navigated to the install directory and installed it all correctly.
However, nothing then happens.
I go back to the front page (http://stats.theendlessnet.uk/3/) and am presented with these errors:

Notice: Undefined index: lolmewnStats in /home/OurAcc/public_html/stats/3/classes/bluestats.class.php on line 91
Fatal error: Call to a member function getAllPlayerStats() on a non-object in /home/OurAcc/public_html/stats/3/plugins/lolmewnStats/modules/topPlayers.php on line 48

Within the Error.log which appears next to index.php, I see the above errors and nothing else.

**Comment by robinp7720** [comment]
You have to enable the lolmewnStats plugin in the configs. Run this query: 

```
UPDATE `BlueStats_config` SET `value`='["lolmewnStats"]' WHERE `option`='plugins' and `plugin`='BlueStats'
```

**Comment by minegame30** [comment]
Okay, ill do that shortly. Where do I put the MySQL details from the Stats plugin? On the "install" page, it used different details. Is this at a later stage from where I am now?

**Comment by minegame30** [comment]
I ran the query in PHPmyAdmin, and still the same errors occur when loading the page.

**Comment by robinp7720** [comment]
All configs are in the BlueStats_config table in the mysql database.
The lolmewnStats mysql settings are where the plugin column equals lolmewnStats. The mysql conifgs are prefixed with MYSQL_ in the options column

**Comment by robinp7720** [comment]
and make sure that the plugins option is ["lolmewnStats"]

**Comment by minegame30** [comment]
Okay, ill look into this tomorrow.

**Comment by minegame30** [comment]
Okay,
Im not sure which column you are referring too. I do not see any MYSQL_ prefixes in the BlueStats_config table. (See image)  
![image](https://cloud.githubusercontent.com/assets/11843354/8041381/c60074e8-0e0f-11e5-8b5b-2a39d5cedfa0.png)

**Comment by robinp7720** [comment]
Simply opening the BlueStats webapp in the browser should create those rows

**Comment by minegame30** [comment]
In your latest changes, I think you might have changed something within the install/MySQL system. I downloaded it and ran it just now in an attempt to try this again, and the webapp does not use the details the user enters on the install page. See below error:
"Warning: mysqli::mysqli(): (28000/1045): Access denied for user 'OurID'@'localhost' (using password: NO) in /home/OurID/public_html/stats/3/classes/plugin.class.php on line 47
There is an error with your theme: global.html not found  "
Despite the fact that I entered another host as opposed to localhost, and I entered a password.
It said that the installation had completed.

Also, as you can see in the error above, the theme seems to be in an odd location. The site cannot find it.

**Comment by robinp7720** [comment]
You probably forgot to set the "MYSQL_password" option. Also, new admin interface at /admin

**Comment by minegame30** [comment]
Whats the username and password for the admin section? Where is that set?

**Comment by minegame30** [comment]
And Im not sure where I am setting the MySQL password. Ive checked the file where it is stored and the details are all correct

**Comment by robinp7720** [comment]
BlueStats Core mysql configs are saved in config.php
Everything else is stored in the database.
The default password and username is "admin".
go to the lolmewnStats plugin and you will see MYSQL_host, MYSQL_username, MYSQL_password, MYSQL_prefix and MYSQL_databse

**Comment by minegame30** [comment]
Okay, give me a few minutes, ill take a look

**Comment by minegame30** [comment]
1) Logged into the admin section and this error: 
![image](https://cloud.githubusercontent.com/assets/11843354/8067736/9251e9b4-0ee7-11e5-841c-d6ebd78765a2.png)
2) Yep, MySQL core details are correct.
3)  A-HA! The configurations in the database have appeared! So can I just ask something, on the install page, are you meant to enter the details for your STATS database, or a different one specifically for BlueStatsWeb? 
4) And theres still something up with the themes. the website will not load now...
![image](https://cloud.githubusercontent.com/assets/11843354/8067829/2c318698-0ee8-11e5-8af0-cf3da8f6bd79.png)

**Comment by robinp7720** [comment]
You are supposed to enter mysql details for the BlueStats app not for lolmewnstats, though, it doesnt matter if they share the same database.
- Install mysqlnd

make sure  themes/default/global.html exists and the themes option is set to default

**Comment by minegame30** [comment]
Okay, thats what I did. Thats fine.
Yep, the themes are there. Ill just check if MySQLnd is installed. Im sure it already is.

**Comment by robinp7720** [comment]
The get_result function is part of mysqlnd, so its not installed.

**Comment by minegame30** [comment]
Okay, Ill contact my host to see what they have to say. Ill let you know :)

**Comment by minegame30** [comment]
Okay, Mysqlnd was not installed. My host are looking into installing it now. 
When it is installed, will the theme work accordingly?

**Comment by robinp7720** [comment]
No, probably not. Make sure the themes option is set to (With quotes) "default"

**Comment by minegame30** [comment]
A-HA! 
Right, progress.
The config in the database was simply set to default, not "default" (there was no quotes).
Adding quotes has fixed it and the site has burst into life.
I assume installing mysqlnd will fix the following error aswell on the highscores page:
Warning: Invalid argument supplied for foreach() in /home/OurID/public_html/stats/3/plugins/lolmewnStats/modules/highscores.php on line 34

**Comment by robinp7720** [comment]
yes it should

**Comment by minegame30** [comment]
Okay, ill let you know when its installed and if it works. Would you like me to write some basic install instructions for other users about changing the database config etc?

**Comment by robinp7720** [comment]
For now that might be very useful! Although I do plan on making it much easier in the future

**Comment by minegame30** [comment]
Sure thing, ill get on it tonight. :)

**Comment by minegame30** [comment]
Added a section to the wiki. Consider linking to it in the readme file?

**Comment by robinp7720** [comment]
Thanks!
