### ISSUE TITLE
Error in highscores

### ISSUE THREAD

**Issue by roastnewt** [robinp7720/Blue-Stats-Minecraft#18]
I get the following error in the highscores page:

Warning: Invalid argument supplied for foreach() in /var/www/html/stats/plugins/lolmewnStats/modules/highscores.php on line 34

Looking for any advice you can supply.

**Comment by robinp7720** [comment]
Your stats are probably empty. Not sure though

**Comment by roastnewt** [comment]
Almost empty - it's on a test server, which only I have joined.  Would that cause an issue?

**Comment by robinp7720** [comment]
Most likely.try populating the database with false stats and players
