### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by ghost** [robinp7720/Blue-Stats-Minecraft#19]
Just installed Bluestats and am getting this error

Unknown error: [2] json_encode(): Invalid UTF-8 sequence in argument. File:/var/www/classes/main.class.php Line:144

Any ideas?

**Comment by robinp7720** [comment]
Try disabling the query cache. Should probably do the trick. Not sure whats going on though.

**Comment by ghost** [comment]
that's fixed that error. Thanks
However now i'm getting 2 more errors and the online player heads don't work anymore

Unknown error: [8] Undefined index: PingInfo. File:/var/www/classes/main.class.php Line:164

and

Unknown error: [8] Undefined index: Online_Players. File:/var/www/classes/main.class.php Line:165

**Comment by robinp7720** [comment]
You probably dont have the correct server details in the configs. Make sure the ip and port is correct and query is enabled on the server

**Comment by ghost** [comment]
it's all correct. Everything was working fine with query caching enabled

**Comment by robinp7720** [comment]
hmm no clue whats going on
