### ISSUE TITLE
Help me..

### ISSUE THREAD

**Issue by Lilmac12312** [robinp7720/Blue-Stats-Minecraft#20]
https://gist.github.com/Lilmac12312/b773c932ba03b2075b5f

**Comment by robinp7720** [comment]
Sorry, I cant help you much. Make sure your using the correct version of BlueStats for lolmewnStats and that your mysql details are correct

**Comment by Lilmac12312** [comment]
It all is correct..

**Comment by robinp7720** [comment]
If your using lolmewnStats 2 use BlueStats 2. Else use bluestats 3

**Comment by Lilmac12312** [comment]
I'm using lolmewnstats 2.0.1-272 w/ bluestats 2
