### ISSUE TITLE
Warning: mysqli::mysqli(): (HY000/2002): Connection timed out

### ISSUE THREAD

**Issue by Mrcoco29** [robinp7720/Blue-Stats-Minecraft#27]
Hey,

I try to install BlueStats. But when I refresh my page i get a lot of errors.

"
Warning: mysqli::mysqli(): (HY000/2002): Connection timed out in /home/myserver/public_html/stats/classes/mysqlPlugin.class.php on line 49

Warning: Error while sending STMT_PREPARE packet. PID=15837 in /home/myserver/public_html/stats/classes/config.class.php on line 125

Notice: Undefined variable: count in /home/myserver/public_html/stats/classes/config.class.php on line 67

Notice: Undefined variable: count in /home/myserver/public_html/stats/classes/config.class.php on line 67

Warning: Invalid argument supplied for foreach() in /home/myserver/public_html/stats/plugins/lolmewnStats/core.php on line 54
Base plugin does not exist: 
Please install this plugin or change the base plugin
Notice: Undefined variable: count in /home/myserver/public_html/stats/classes/config.class.php on line 67

Notice: Undefined variable: count in /home/myserver/public_html/stats/classes/config.class.php on line 67

Notice: Undefined variable: count in /home/myserver/public_html/stats/classes/config.class.php on line 67

Notice: Undefined variable: count in /home/myserver/public_html/stats/classes/config.class.php on line 67
....
"

stats3 is installed on the db, but blue stats can't...

Could you help me ?

-- I'm french, sorry for my bad english

Mr_coco29

**Comment by robinp7720** [comment]
Try adding 

``` php
ini_set("default_socket_timeout", 6000);
```

to the beggining of index.php and tell me if it works

**Comment by Mrcoco29** [comment]
It's very long to load and i get the same error. 

(I want improve my english, say me if i do big error :p)

**Comment by robinp7720** [comment]
**The page takes** very long to load and i get the same error. 

Hmm ok, does the BlueStats database and table exist? If yes, is there anything inside the   BlueStats_config table?

**Comment by Mrcoco29** [comment]
The BlueStats_config table exists and contains all informations on the config.

**Comment by robinp7720** [comment]
DId you go to /admin on your webbrowser? If not, go to it, enter "admin" as username and password then go to /admin/advanced

**Comment by Mrcoco29** [comment]
I have already been on the admin panel. However I have a 404 error to mywebsite.com/admin /advanced.

**Comment by Mrcoco29** [comment]
error_log file : http://pastebin.com/Uv3s51HP (the first error is not the same than before)

**Comment by robinp7720** [comment]
Sorry for the long delay. But this seams to be an error with your database or with your PHP installation.

**Comment by Mrcoco29** [comment]
Super...

**Comment by robinp7720** [comment]
I'd recommend to try a clean install of php directly from your package manager without changing in of the php configs.

**Comment by Mrcoco29** [comment]
I'll do it alone ... Thanks. (Just, if you go on http://yourdomain.com/config.json we can see our db config.

**Comment by robinp7720** [comment]
Thanks for reporting this! I'm supprised no one has reported that yet. The reason I'm not helping you with the problem is because I honestly don't know how to fix it. No one else has gotten the problem and I'm not able to reproduce it.

**Comment by Mrcoco29** [comment]
yeah, I understand ^^ if I find, I'll tell you.

**Comment by Mrcoco29** [comment]
It was the MySQL server IP who was not allowed in the firewalls of the web server... Thank !
