### ISSUE TITLE
Can't write to Assests or Cache.

### ISSUE THREAD

**Issue by LigerXT5** [robinp7720/Blue-Stats-Minecraft#30]
I recently done a fresh install of Stats3 and Bluestats 3.
Upon accessing /install, it stats that Assets and Cache cannot be written to, however, the whole directory that holds Blue is currently set to 777.

Finishing the install, the follow appears on the last step.

Warning: scandir(../../themes/material/assets): failed to open dir: No such file or directory in /usr/www/mcden/public/stats/install/views/step4.php on line 133

Warning: scandir(): (errno 2): No such file or directory in /usr/www/mcden/public/stats/install/views/step4.php on line 133

Warning: array_diff(): Argument #1 is not an array in /usr/www/mcden/public/stats/install/views/step4.php on line 133

Warning: Invalid argument supplied for foreach() in /usr/www/mcden/public/stats/install/views/step4.php on line 135

**Comment by silelmot** [comment]
i added the both folders by hand before the install and set them to 755 and this worked... maybe try!

**Comment by LigerXT5** [comment]
What do you mean you added both folders by hand. As in created the folders then dropped the files inside?

**Comment by silelmot** [comment]
when the install-routine told me, that these two folders are missing i created them in the root-directory. than hit F5 and install routine was fine with everything...

**Comment by robinp7720** [comment]
Late reply, sorry. Just chmod 775 the assets and cache directory and make sure that the user running php (Most likely your webserver eg www-data) owns the files
