### ISSUE TITLE
how to add new infos

### ISSUE THREAD

**Issue by silelmot** [robinp7720/Blue-Stats-Minecraft#31]
hello. i installed an achivement plugin and tried to add a list in the players-section in bluestats, but i dont understand the php-code.
can you give a hint or maybe a samplefile how to add infos that are stored with an externel plugin in the same mysql-database?

**Comment by robinp7720** [comment]
Most mysql databases of Minecraft plugins are pretty similar. BlueStats should be able to handle most databases with just a few lines of code. See the McMMO plugin for a very simple plugin. To add info to the player pages, you have to create a module for the BlueStats plugin. All the McMMO plugins are relativly simple and easy to understand
