### ISSUE TITLE
Error with the .htaccess file.

### ISSUE THREAD

**Issue by ShayPunter** [robinp7720/Blue-Stats-Minecraft#32]
I am unable to use the web GUI due to a error in the .htaccess file, the error is here:

[Wed Apr 06 16:52:22.061673 2016] [core:alert] [pid 14506] [client 107.170.166.118:37465] /var/www/html/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration.

Anything I can do?

**Comment by smc87** [comment]
enable mod-rewrite for apache?

Try this:
http://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2
