### ISSUE TITLE
anyway to get PvP Deaths?

### ISSUE THREAD

**Issue by smc87** [robinp7720/Blue-Stats-Minecraft#35]
As Title

**Comment by smc87** [comment]
Thank you

**Comment by smc87** [comment]
;Hopefully a quick question, if i was on the admin page how would I now add PvP Deaths to the top players lists? 
Currently "pvp" still seems to point to pvpkills. eg:
["words_said","votes","pvp"]

**Comment by robinp7720** [comment]
@smc87 This would be possible with the Deaths table. To display only pvp deaths though, you would need to change the way it gets the highscores though. Open a new issue with this and I might add this to BlueStats! Thanks for using it too! :)
