### ISSUE TITLE
bubbleStats not working

### ISSUE THREAD

**Issue by Langleu** [robinp7720/Blue-Stats-Minecraft#37]
for whatever reason the bubbleStats are not working properly for me.
![bubblenotworking](https://cloud.githubusercontent.com/assets/9141483/14606683/91226436-057e-11e6-8ce4-77d1d30f45bf.png)

**Comment by robinp7720** [comment]
Go to /admin/advanced/actions/setupTheme.php to setup your theme.
Make sure bluestats as write permissions to /assets

**Comment by Langleu** [comment]
funny as it is, but I can't access that site, neither can I change my theme.
Had no problem installing BlueStats.
/assets is empty, and yes write permission is set.

**Comment by robinp7720** [comment]
Go to /admin to login into the admin panel first

**Comment by Langleu** [comment]
Did that, but it returns a 500, site not working

**Comment by robinp7720** [comment]
I will need some errors to help you any further. Give me the last few lines from _/var/log/apache/error_log_ If your running apache

**Comment by Langleu** [comment]
`[Mon Apr 18 09:51:58 2016] [error] [client 127.0.0.1] File does not exist: /var/www/vhosts/random/stats/robots.txt`
`[Mon Apr 18 17:10:46 2016] [error] [client 127.0.0.1] File does not exist: /var/www/vhosts/random/stats/assets/style.css, referer: random`

that pretty much sums up the latest errors.

**Comment by robinp7720** [comment]
Those are not the errors that are causing the 500 http error. If you want a fix for the 500 error, please send me atleast the last 3 entries in the error log.

A quick fix for the missing css file is to copy /themes/bigBlue/assets/style.css to /assets/style.css

**Comment by Langleu** [comment]
http://pastebin.com/GeUC2VdG
hope that helps a bit more

**Comment by robinp7720** [comment]
Clear the /cache folder and copy the theme assets into the assets folder
