### ISSUE TITLE
Issue after removing /install

### ISSUE THREAD

**Issue by itismejoey** [robinp7720/Blue-Stats-Minecraft#40]
Hello there!

I was able to complete the install with no issues. This was until I removed the /install folder (as instructed) , then I wasn't able to access the main page. Just got a "page isn't working error". I can still access the /admin page perfectly fine.

Speaking of admin page... How do I set the login info or is that not a thing yet?

PS: You should drop a blank index.php file in each folder (ie themes, plugins, etc) so nosey people don't get to see inside the directories. 👍

**Comment by robinp7720** [comment]
Please give me an error log from php or else I will dismiss this.
apache access files take care of the problem. If you use nginx, you must create your own config

**Comment by itismejoey** [comment]
1. There is no error.log
2. I don't even know to what question you are answering to for the second part.

**Comment by robinp7720** [comment]
Your php error logs. They should be in /etc/apache/error.log if you're using apache.

**Comment by itismejoey** [comment]
Once again, there is no error.log and I am using apache. I know what a php error looks like and this isn't one.

It's just a blank screen, when I use Safari and when using Chrome it's

```
The [ADDRESS] page isn’t working

[ADDRESS] is currently unable to handle this request.
```

**Comment by itismejoey** [comment]
Thanks for the help...

**Comment by ultimate255** [comment]
I had the same issue. Make sure you specify a Query IP and Port when installing. Also the default login for the admin page is
Username: admin
Password: admin
Hope that helps
