### ISSUE TITLE
Individual player URLs not working correctly

### ISSUE THREAD

**Issue by o355** [robinp7720/Blue-Stats-Minecraft#49]
At least in my server of BSM, the individual player URL is outright different versus what's on the demo site, and the difference in the URLs make it so I can't access the individual player URLs.

My URL:
example.com/player/uuidgoeshere

Demo URL:
example.com/?page=player&id=usernamegoeshere

Pretty sure it's a bug, but I don't know really.

**Comment by o355** [comment]
Sorta self figured it out, the player URL is bugged in the SQL config, on line 27. Here's the entry:

"http:\/\/mywebsitehere.com\/{page}\/{player}\/"

And the change needed to be propagated to SQL by doing:
"http:\/\/mywebsitehere.com\/?page=player&id={player}"

So I'm assuming this is an SQL glitch.

There's also the fact that by default, URLs themselves glitch too, not adding ?page={page} onto them from installation. I had to manually go about files to fix that glitch.

**Comment by robinp7720** [comment]
This is not a bug but an intendented feature making use of apache rewrites. I use nginx on my server on which I have not setup these rewrites. Better page routing is coming in the future.
