### ISSUE TITLE
windows error posix not existing

### ISSUE THREAD

**Issue by Jamie4224** [robinp7720/Blue-Stats-Minecraft#52]
I'm trying to use bluestats on a windows server 2012 VPS but it says the posix function does not exists, thats right, i know that function does not works on windows, but is there any way to get BlueStats working?

**Comment by robinp7720** [comment]
BlueStats is not designed to run on windows nor do I have a testing enviroment to attempt to make it compaitble with windows. Nor do I have any intentions to ever make BlueStats compatible with windows.
