### ISSUE TITLE
Player Last Seen/Last Joined times are way off

### ISSUE THREAD

**Issue by o355** [robinp7720/Blue-Stats-Minecraft#54]
So, I've discovered after having BSM online for a few weeks, that for a good amount of users, their last joined/last seen times are outright off. At least for my profile, the program indicates I was last online 2 weeks ago on my server, which isn't true, and doesn't update when a user comes online.

The databases are completely functional and update with other stats.

**Comment by robinp7720** [comment]
After looking at this, I wonder to myself how I never noticed that problem would exist. Took a while, but thanks for reporting it!
