### ISSUE TITLE
CoreProtect Stats?

### ISSUE THREAD

**Issue by ntimo** [robinp7720/Blue-Stats-Minecraft#55]
Hello,
could you maybe add a plugin to generate Stats using the core protect plugin? So that when using it there is no extra stats plugin needed.

Thx
Timo :)

**Comment by robinp7720** [comment]
This is on my todo list and have already started somewhat on this. First I'm revamping the plugins system to allow for more dynamic mysql database layouts. The main problem though is the speed. CoreProtect is designed to log changes, not stats.

**Comment by ghost** [comment]
I agree with @robinp7720, My CoreProtect database is currently about 5Gb. It would take ages to index all a users data, and make stats out of that. It may be a one- time conversion thing, but that might be better of to the developer of the stats plugin. You do have to install stats then, But i hope that that isn't a real big problem as it's quite lightweight (compared to CoreProtect.)
