### ISSUE TITLE
Error 404 "Not Found"

### ISSUE THREAD

**Issue by LegendaryThierry** [robinp7720/Blue-Stats-Minecraft#59]
Hello,

I got the error 404 when I click on the "highscores" and "All Players". I don't have any .htaccess file in my /www/html/ directory.

The BlueStats' main page is working : http://apocalypsez.xyz/stats/

Highscores : http://apocalypsez.xyz/stats/highscores/
All Players : http://apocalypsez.xyz/stats/allPlayers/

Thanks in advance for your help :). And sorry for my ticket about the administration panel, the interface wasn't really intuitive to me.

**Comment by robinp7720** [comment]
Enable http rewrites in apache

**Comment by LegendaryThierry** [comment]
I enabled the http rewrites in Apache as you advise me to do. However, I'm still disturbed by the behavior of my highscores and All Players pages because they show me my website's home page.

What should I do to fix that ?

My main page : http://apocalypsez.xyz/
Highscores page : http://apocalypsez.xyz/stats/highscores/
All Players page : http://apocalypsez.xyz/stats/allPlayers/

Thanks again for your help. :)

**Comment by robinp7720** [comment]
in the .htaccess file replace `RewriteBase /` with `RewriteBase stats/`

**Comment by LegendaryThierry** [comment]
Unfortunately, it didn't work :(
Now, I have an error 500. http://apocalypsez.xyz/stats/
However, when I put back `RewriteBase /` instead of `RewriteBase stats/`, I can access the main page of BlueStats.

**Comment by robinp7720** [comment]
Give me the last 5 lines of your php error log. Should be located in /var/logs/apache/error.log

**Comment by LegendaryThierry** [comment]
> [Mon Aug 29 10:23:15.412035 2016] [core:alert] [pid 16216] [client 88.153.7.15:6                                                                                                                     4066] /var/www/html/stats/.htaccess: RewriteBase: argument is not a valid URL, r                                                                                                                     eferer: https://github.com/
> [Mon Aug 29 10:28:57.360676 2016] [:error] [pid 16215] [client 185.25.148.240:49                                                                                                                     194] script '/var/www/html/testproxy.php' not found or unable to stat

**Comment by robinp7720** [comment]
Sorry, try adding a slash before the stats/. so make it RewriteBase /stats/

**Comment by LegendaryThierry** [comment]
Thanks, it works perfectly now :).
