### ISSUE TITLE
Custom PHP build?

### ISSUE THREAD

**Issue by gerardvanschip** [robinp7720/Blue-Stats-Minecraft#63]
I was getting the dreaded "mysqlnd  (Please install mysqlnd)" which I see many other people struggled with so I contacted my hosting company who investigated the install script and came back to me saying that bluestats needs a custom compile of PHP?

Seems a bit much so my question is this. Is this true, is my host just spinning stories or is this a bug and it should work but I did something wrong?

**The reply from my host:**
The aforementioned script checks whether mysqli_fetch_all() function exists. Otherwise, returns "Please install mysqlnd" message (like in your particular case). As you may know mysqli extension supports persistent connections when using either MySQL Native Driver (mysqlnd) or MySQL Client Library (libmysqlclient). In other words: mysqli can be either compiled against the MySQL Client Library in order to use its client-server protocol or it can be compiled to use MySQL Native Driver instead of the MySQL Client Library. CloudLinux environment implies the MySQL Client Library usage, whilst the MySQL Native Driver is simply a part of the official PHP sources as of PHP 5.3.0 (that's why we can turn it on in the PHP Selector interface). The thing is that the mysqli_fetch_all() function is available only when mysqli is compiled to use MySQL Native Driver (which requires certain compile time options like --with-mysqli=mysqlnd). 

That's why your installation script refuses to work. Unfortunately it requires a custom PHP build, which can not be offered by our shared hosting environment.

**Comment by robinp7720** [comment]
just go to /install/index.php?step=2 to skip the checks. Make sure you have all the other dependencies though. MySQLnd as far as I know is not required anymore, but for not having tested it without it installed I havent removed it from the checks

**Comment by gerardvanschip** [comment]
Hi. Tried that, filled in all the info requested, hit submit and after a 2 min wait get greeted with a "page not found" at the stats/install/?step=3 address.

**Comment by robinp7720** [comment]
Sorry for the long wait, but as I have previously discovered, MySQLnd is still required by BlueStats. To remove this requires an extensive refactor of mysqli function calls. This will not occur due to mysqlnd being both faster and more ram efficient then libmysqlclient. I however recommend you to request an updated php version from your host as php 5.3.0 was released in 30 Jun 2009 which makes it 7 years old at this time of writing.
