### ISSUE TITLE
Error when sockets disabled in php

### ISSUE THREAD

**Issue by gerardvanschip** [robinp7720/Blue-Stats-Minecraft#64]
First I got stuck on step 1 where it asked for mysqlnd which is installed. The dev told me to ignore that and go to step 2 "stats/install/?step=2" so I did that manually, entered all the details, hit submit. It sat there for a few minutes and then came back with "Oops, page not found" at stats/install/?step=3

Lost as what to do.

**Comment by robinp7720** [comment]
I'm guessing this is a problem relating to socks and the query plugin. I will be added a check for this to the installation script when I can. The solution to the problem would be to ignore the McQuery options in the config panel. Alternatively request your host to enable sockets.

**Comment by robinp7720** [comment]
Fixed in latest commits
