### ISSUE TITLE
Admin Page & Stats Page is not working

### ISSUE THREAD

**Issue by crysis992** [robinp7720/Blue-Stats-Minecraft#65]
Getting a error right after installation. 
All data is set correctly. (Using a different database for BlueStats than the Stats3 plugin)

Link to the stats page (Fresh installation with debug enabled)
https://crytec.net/stats/?page=home

The Admin page login works fine, but unable to click on any menu except the security thing and advanced. Advanced is giving me following error:
`Fatal error: Call to undefined method mysqli_stmt::get_result() in /var/www/crytec/stats/admin/advanced/parts/plugins.php on line 17`

**Comment by robinp7720** [comment]
I removed the dependency check for mysqlnd but as it turns out, I didn't remove the need for mysqlnd. The solution is to install mysqlnd using you system's package manager.
