### ISSUE TITLE
Location for servername/URL

### ISSUE THREAD

**Issue by Yamanipanuchi** [robinp7720/Blue-Stats-Minecraft#67]
This is just a suggestion/enhancment. If someone were looking at the site, There's nothing to tells the user what server stats there looking at. Just a small section with two lines "Servername" and "Server ip/domainame" Yes, Most would think this is something someone would assume. But, well there are a lot of interesting people out there!

**Comment by robinp7720** [comment]
The themes engine allows server admins to completely change the way the site looks, including adding and removing text. There is also a built in module which shows the server name value set in the admin panel. I will be adding documentation for the themes engine and plugins engine soon.

Thanks for the suggestion though!
