### ISSUE TITLE
Hey my issue is about the Bluestats installer and the Query IP and the Query Port!

### ISSUE THREAD

**Issue by torstenlemke** [robinp7720/Blue-Stats-Minecraft#68]
Hey like you can See in the Title I don't know what should I write into these two fields?
Which Server Query Port and URL?
The Files are located Website -> stats -> install
Thank you and Sorry for my bad English I'm from Germany!

**Comment by robinp7720** [comment]
You have to enable server query on your minecraft server first. Then enter the ip of your minecraft server and the port for the query which is most likely the default 25565
