### ISSUE TITLE
Highscores and TopPlayers empty

### ISSUE THREAD

**Issue by ghost** [robinp7720/Blue-Stats-Minecraft#69]
Hello there, I just recently installed BlueStats. It is really awesome, 
But The highscores are always empty. I did i reinstall, and downloaded the recent stable. There are no errors in the (web) Server logs. I am using Apache2 and `PHP 7.0.13-0ubuntu0.16.04.1` 
There are currently 7 Players on In the LolMwewnstats Database. Setting the limit to For example 5 does not help.
Also, The TopPlayers are all Nobody.
If you need to know any more, Just ask me.

Thanks, Tim

**Comment by robinp7720** [comment]
In index.php set $debug to true and give me any errors which occur.

**Comment by ghost** [comment]
with `$debug = true;` in index.php i am seeing no errors on the page itself, nor in apache's logs. I also did a complete reinstall on a vm and got the exact same problems. I can send you the database if that affects anything?

**Comment by robinp7720** [comment]
Sorry for the long wait.

I just committed code which should output mysql errors when debug mode is enabled. I'm guessing this is a problem to do with the ```ONLY_FULL_GROUP_BY``` sql mode which seams to be default now in many mysql installations. A temporary fix can be found here: http://stackoverflow.com/questions/23921117/disable-only-full-group-by. I need to change the database queries to support the mode which will hopefully come soon :)

**Comment by ghost** [comment]
same problems, i'll do a bit more debugging later. ~Also i may notice you that in index.php the debug switch is set to `$debug = flase;` by default, which causes the /install removal thing to not work successfully.~

**Comment by ghost** [comment]
It worked ;D
As shown in the stackoverflow thread you linked me, the `SET sql_mode = ''`
SQL command does **Not** work _Atleast on my system_, but the
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`
Command did the trick for me.
Thanks for your support!
