### ISSUE TITLE
Call to undefined method mysqli_stmt::get_result()

### ISSUE THREAD

**Issue by wioxjk** [robinp7720/Blue-Stats-Minecraft#75]
After Installing Bluestats, I get the following error message in the webrowser.

`Fatal error: Call to undefined method mysqli_stmt::get_result() in /var/www/html/minecraftstats/plugins/lolmewnStats/core.php on line 88`

Running PHP 5.6.30-0+deb8u1 toghether with Apache/2.4.25
All the files is owned my the same user.

Apache error log:

`[Wed Feb 22 11:40:07.189158 2017] [:error] [pid 35622] [client 193.14.90.12:64329] PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() in /var/www/html/minecraftstats/plugins/lolmewnStats/core.php on line 88, referer: https://mc.selea.se/minecraftstats/install/?step=4`

EDIT:

Tried to install in the documentroot on a separate virtualhost. Got this message during "stage 4":

```
Warning: scandir(/var/www/stats/themes/webstatx/assets): failed to open dir: No such file or directory in /var/www/stats/install/views/step4.php on line 147
Warning: scandir(): (errno 2): No such file or directory in /var/www/stats/install/views/step4.php on line 147
Warning: array_diff(): Argument #1 is not an array in /var/www/stats/install/views/step4.php on line 147
Warning: Invalid argument supplied for foreach() in /var/www/stats/install/views/step4.php on line 150
```

Also got a 404 on the site after installation was completed.
Changing PHP from 5.6 to PHP7.0, this appears in the browser;

`Fatal error: Uncaught Error: Call to undefined function xPaw\mb_convert_encoding() in /var/www/stats/plugins/query/minecraftQuery.php:108 Stack trace: #0 /var/www/stats/plugins/query/minecraftQuery.php(35): xPaw\MinecraftQuery->GetStatus('\x00\xE9\x10,') #1 /var/www/stats/plugins/query/core.php(24): xPaw\MinecraftQuery->Connect('MYDOMAIN', '25565') #2 /var/www/stats/index.php(70): query->__construct(Object(mysqli)) #3 {main} thrown in /var/www/stats/plugins/query/minecraftQuery.php on line 108`

**Comment by robinp7720** [comment]
MySQLnd is not installed on your system. The installer check far it has been fixed in the latest commit.

**Comment by wioxjk** [comment]
@robinp7720 
mysqlnd is installed.

**Comment by wioxjk** [comment]
So I guess this is fixed?

**Comment by robinp7720** [comment]
It was never a problem with MySQLnd. It was a problem with the theme setup and query which I could never reproduce.

**Comment by wioxjk** [comment]
Alright!
