### ISSUE TITLE
ONLY_FULL_GROUP_BY caused Highscores list is empty

### ISSUE THREAD

**Issue by Viktorx3** [robinp7720/Blue-Stats-Minecraft#76]
Hello, first of all I am not sure if this is the right place to post this but today I installed BlueStats with LolmewnStats. The installation was successful but I have this one problem:
There are no players listed on the highscores. On the front page are only "Nobody" users listed. Everything else works just fine.

I saw this post: https://github.com/robinp7720/Blue-Stats-Minecraft/issues/69. They may found a solution for that, but the problem is that i don´t know how I can fix it. I am pretty new to all this stuff and I am setting everything up in Plesk.

Hope you can help me, thanks!

**Comment by ghost** [comment]
Are you able to get access to the server's console, or do you have phpmyadmin installed?
_______________________________________________________________
edit: In plex go to:
Tools & settings -> Database servers, and select the right server. Then you'll end up in phpmyadmin.
On the top most bar you'll see a tab called SQL
Click on that, then paste the next code in the text box:
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`
Then press "continue"
It should be working right now.
_notice if the server reboots this setting will be gone and you might have to repeat the above._

**Comment by Viktorx3** [comment]
First thank you for your answer! But I feel a bit lost. I tried that but it says i need SUPER privileges.

**Comment by ghost** [comment]
It's likely that you host the website at a shared host, So i think your phpmyadmin isn't linked to a root account on the sql server, So you may really kindly ask them to enter it in the server's mysql console. But as it's a shared host that might break other sites, So i guess they won't (but you can atleast try it) Else you could hope that @robinp7720 updates the Sql statements soon.

**Comment by Viktorx3** [comment]
Hm well alright. It's weird because everything works and tracks the statistics but not the highscores. Maybe he will fix it. I have hope :)

**Comment by robinp7720** [comment]
Should now be fixed. @Viktorx3 @timvanbavel, could you please test it?

**Comment by ghost** [comment]
Nope, still same issues. It has to do with the sql command at plugins/lolmewnStats/core.php line 75.
Due to the same error as #69 the use of `GROUP BY` and `ORDER BY` is no longer supported .
Also, i always update by just changing the files, not everything. But when i tried to create a new site, It failed at the Install first page. as shown [Here](http://test.timvanbavel.com), i think this has to do something with #75.
The things in #77 do work tho :D

**Comment by Viktorx3** [comment]
Any updates ?

**Comment by robinp7720** [comment]
Fixed! :) Please Re-Pull the repo and test

**Comment by Viktorx3** [comment]
Amazing! It works, Thank you!

**Comment by Viktorx3** [comment]
![bug](https://cloud.githubusercontent.com/assets/26068226/23670983/e4169d6c-0369-11e7-8f50-89e5862921b5.PNG)

Okay that happens now...

**Comment by robinp7720** [comment]
@Viktorx3 fixed :)

**Comment by Viktorx3** [comment]
Nice! Do I have to install everything again or what files do I need to update ?

**Comment by ghost** [comment]
replacing /plugins/lolmewnStats/modules/topPlayers.php should do the trick.

**Comment by robinp7720** [comment]
I would recommend you to clone the repo using git and doing a git pull when an update comes out

**Comment by Viktorx3** [comment]
Okay it works now! But I have one suggestion: It shows traveled 51821.778768308 blocks, can you make the number rounded?

**Comment by ghost** [comment]
I already mentioned that in #78, but still haven't got a respond on that.

**Comment by Viktorx3** [comment]
Oh okay good, sorry for that. And what happened here: 
![image](https://cloud.githubusercontent.com/assets/26068226/23703602/068f4604-0401-11e7-9c2b-383156e784f2.png)

**Comment by ghost** [comment]
Well, it was more meant as a reminder for @robinp7720 

also, I got the exact same things happening.

it looks like this at mine:
(notice 5, 6 & 7)
![image](https://cloud.githubusercontent.com/assets/24352731/23703826/27adcc92-0402-11e7-897b-15d9ff48bbb6.png)

**Comment by Viktorx3** [comment]
Any updates  on this ? The play time is very messed up, it says i played for 20 minutes but i played way more than that. It was up on 50 (i also played more than 50 mins) but now its on 26 again.
