### ISSUE TITLE
[Enchantment/fix] Playtime as 2 days and 0 hours & last join is an timestamp

### ISSUE THREAD

**Issue by ghost** [robinp7720/Blue-Stats-Minecraft#77]
Well title says most, This is all in the Highscores tab.

2 examples:

![image](https://cloud.githubusercontent.com/assets/24352731/23487363/d5cae692-fee5-11e6-9f3e-73781d961fb2.png)
------
![image](https://cloud.githubusercontent.com/assets/24352731/23487377/eda5adf6-fee5-11e6-9119-2bbea7684513.png)

**Comment by robinp7720** [comment]
I'm assuming your saying that "2 days and 0 hours" should be "2 days" and the time stamp should be displayed in the same way?

**Comment by ghost** [comment]
yep, it should be "2 days", and the time stamp to be an acual readable time.
