### ISSUE TITLE
[Tiny enchantment] Rounding numbers like Blocks Traversed

### ISSUE THREAD

**Issue by ghost** [robinp7720/Blue-Stats-Minecraft#78]
Currently Block Traversed shows like `2037343.47056`, the same for Damage taken. It would be the most pleasant for users to have that show like a rounded number.

**Comment by robinp7720** [comment]
This has already been fixed

**Comment by ghost** [comment]
@robinp7720 i just reinstalled the whole system, and i believe this is not yet fixed.
You can see it at this page:
http://test.timvanbavel.com/player/ef580819-3aad-45d9-8945-04554393d237/
