### ISSUE TITLE
lolmewnStats end of life

### ISSUE THREAD

**Issue by ardentcrest** [robinp7720/Blue-Stats-Minecraft#83]
As Lolmewn is not updating the stats anymore could you add statz to this great program.

And as lolmewnStats is not used by autoranks and a few others, its silly to have two stat plugins running at the same time.

**Comment by robinp7720** [comment]
@ardentcrest Well, I didn't notice that actually. I will be adding a statz plugin soon then for BlueStats! Currently I'm busy with school work though so it may take a while.

**Comment by robinp7720** [comment]
Statz support added
