### ISSUE TITLE
Minecraft Query Issue

### ISSUE THREAD

**Issue by TheUpBeatGamer** [robinp7720/Blue-Stats-Minecraft#84]
Hello!

I keep getting this issue when I try and put the correct information into the boxes. Please help!

Notice: fwrite(): send of 7 bytes failed with errno=1 Operation not permitted in /home/crapdfpy/public_html/stats/plugins/query/minecraftQuery.php on line 57
 Server query failed

Thanks!

**Comment by TheUpBeatGamer** [comment]
I have fixed this issue, your host needs to open the UPD port instead of the TCP port of your server query!

**Comment by robinp7720** [comment]
Interesting. Should add a detection script to explain the error to the user on install
