### ISSUE TITLE
LiteBans plugin

### ISSUE THREAD

**Issue by TheUpBeatGamer** [robinp7720/Blue-Stats-Minecraft#85]
LiteBans is great and if it could be implemented into BlueStats that would be great so you can check players that have been banned and also have its own page where it shows you the recent bans, kicks, mutes.

LiteBans saves to a database so I think this would be pretty good to add.

Spigot Page - https://www.spigotmc.org/resources/litebans.3715/

Thanks!

**Comment by robinp7720** [comment]
This may be fairly late now, but BlueStats now has support for LiteBans!
