### ISSUE TITLE
Add TotalTracker Plugin

### ISSUE THREAD

**Issue by bittiez** [robinp7720/Blue-Stats-Minecraft#87]
Hey there, I am the author of [TotalTracker](https://github.com/bittiez/TotalTracker/), I would love to see integration into your project, unfortunately I don't a lot of documentation on how to create a plugin, is this something you do on your own, or could you provide some instructions and I can create a pull request for my own?

**Comment by robinp7720** [comment]
I'm currently rewriting the Plugins api within BlueStats so it's easier to make plugins for it, because truth be told, I don't know how the plugins api works completely anymore. When the new api is finished I will make a thorough documentation of it! :)

So yes, I want to make the API available to developers to integrate their own plugins into it.

**Comment by bittiez** [comment]
Is there any time frame for this? Or a branch to see progress? Sorry I'm just curious

**Comment by robinp7720** [comment]
@bittiez Sorry for the extremely late reply. While the new API is under development, the release of the new api may be a little off into the future. I've got an almost complete design of the new api: https://github.com/robinp7720/Blue-Stats-Minecraft/wiki/New-plugns-api so development should not take too long. It is however very close to the end of the school year for me which means a lot of deadlines which I need to reach.

So I do not have a time frame for this, I however will complete this as soon as I can.

**Comment by robinp7720** [comment]
@bittiez The new plugins system is essentially done and plugins should be far easier to make now. If you look at the Statz plugin in the newPluginSystem branch you should be able to figure out how to make a plugin. I'll make a documentation for the system later this week.

**Comment by robinp7720** [comment]
@bittiez Is there still interest in this plugin being integrated with BlueStats? If so, provide me with a database layout scheme and export of data and I will add the plugin to BlueStats

**Comment by robinp7720** [comment]
If interest is regained, please reply. I'm closing the issue for now
