### ISSUE TITLE
Hour(s) missing in time summary (Last Seen, Play Time)

### ISSUE THREAD

**Issue by ingermaa** [robinp7720/Blue-Stats-Minecraft#89]
Hours is missing in time summary for "Last seen" and "Played" time.

Example from Played time top list:

1. 14 mins and 36 seconds
2. 17 mins and 1 second

The sorting seems to be ok, but the rendered time on the page is missing hour(s) and does not look correct.

**Comment by robinp7720** [comment]
Since you already fixed this in your own branch, I'd welcome a pull request!
