### ISSUE TITLE
Server Query always fails

### ISSUE THREAD

**Issue by ChrisLane** [robinp7720/Blue-Stats-Minecraft#92]
I'm going through the installer pages and don't seem to be able to get the server query to work.

I've tried leaving the port number out to use the SRV DNS record, I've tried putting the port number in, I've tried different servers, I've set "enable-query" to true in the server settings and still, nothing works.

I don't see any errors in my apache error log.

Any ideas?

**Comment by robinp7720** [comment]
Maybe this helps: https://github.com/robinp7720/Blue-Stats-Minecraft/issues/84
Other than that this does not relate to this project. The most recent commit adds the ability to disable the query on install
